apiVersion: apps/v1
kind: Deployment
metadata:
 name: staff-service-risky
spec:
 selector:
   matchLabels:
     version: risky 
     app: staff-service
 replicas: 1
 template: # template for the pods
   metadata:
     labels:
       version: risky
       app: staff-service
   spec:
     containers:
     - name: staff-service
       image: richardchesterwood/istio-fleetman-staff-service:6
       env:
       - name: SPRING_PROFILES_ACTIVE
         value: production-microservice
       ports:
       - containerPort: 8080